# Generated by Django 5.2.1 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_profile_full_name_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='facility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
