# Generated by Django 5.2.1 on 2025-05-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_meetingroom_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='facility',
            new_name='facilities',
        ),
    ]
